runtime: nodejs18
instance_class: F2

env_variables: 
  BUCKET_NAME: "your-ng-app-bucket"

handlers:
- url: /
  static_files: dist/csci571_assignment8/index.html
  upload: dist/csci571_assignment8/index.html

- url: /
  static_dir: dist/csci571_assignment8